### ISSUE TITLE
URLs pulling in IPs

### ISSUE THREAD

**Issue by punkrokk** [InQuest/python-iocextract#34]
If I have a URL with a port - e.g. 1.1.1.1:449 I'm seeing a URL getting extracted in the format of: 
http://1.1.1.1:449.

Is that desired behavior?

**Comment by punkrokk** [comment]
bump

**Comment by luis261** [comment]
I have the same problem, even if no port is given, if the IP is defanged.
![grafik](https://user-images.githubusercontent.com/72552948/114734929-fc3b1700-9d44-11eb-8d86-c2a8e4cc439b.png)

**Comment by azazelm3dj3d** [comment]
Hi, @punkrokk!

This issue is now resolved and available in the develop branch. I will send another comment here once a new version is available for download from PyPI.

Here's an example with the new code:
```python
import iocextract

def extract_no_scheme_urls():
    url = "1[.]1[.]1[.]1:443"
    print(list(iocextract.extract_urls(url, refang=True, no_scheme=True)))

extract_no_scheme_urls()
```

**Comment by azazelm3dj3d** [comment]
New version is now available on PyPI: https://pypi.org/project/iocextract/1.14.0/

**Comment by luis261** [comment]
> New version is now available on PyPI: https://pypi.org/project/iocextract/1.14.0/

@azazelm3dj3d while it seems like the bug originally referenced in this issue is fixed in the new version, the one I commented above still exists. Defanged IPs still get extracted by `extract_urls` while their non-defanged counterparts don't
